[package]
name = "rust_reduced_row_echelon_form"
version = "0.1.0"
authors = ["Trevor <65122083+TPXS@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
